-- delete table if it exists

drop table if exists bookmarks;

-- create the bookmarks table

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title VARCHAR(80) NOT NULL,
    url VARCHAR(80) NOT NULL,
    rating INTEGER default 3,
    description VARCHAR(80)
);

-- insert data into the table

insert into bookmarks (title, url, rating, description)
values
('Thinkful', 'https://www.thinkful.com', 5, 'Think outside the classroom'),
('Google', 'https://www.google.com', 5, 'Where we find everything else'),
('MDN', 'https://developer.mozilla.org', 5, 'The only place to find web documentation'),
('Reddit', 'https://www.reddit.com', 1, 'Where to find nothing of value'),
('Twitter', 'https://www.twitter.com', 3, 'Say anything in 280 characters'),
('Facebook', 'https://www.facebook.com', 2, 'Where to connect with friends, family, and weird people from your high school'),
('CNN', 'https://www.cnn.com', 3, 'Breaking news and videos'),
('Github', 'https://www.github.com', 5, 'The best place to store and share your programming work'),
('Amazon', 'https://www.amazon.com', 4, 'Shop for anything in a vast online store'),
('eBay', 'https://www.ebay.com', 5, 'Bid, buy, and sell online');
